#!/bin/bash

EXIT=0

function search_warning {
    OUTPUT=''
    PATTERN=$1
    FILES=$2
    while read name; do
        git diff --cached $name | grep -E "^\+.*$PATTERN" &> /dev/null
        if [ $? -eq 0 ]; then
            OUTPUT=$OUTPUT${OUTPUT:+"\n"}$name
        fi
    done <<< "`
        if [ -z $FILES ]; then
            git diff --cached --name-only
        else
            git diff --cached --name-only | sed -e "/\.\($FILES\)$/!d"
        fi
    `"
    if [ -n "$OUTPUT" ]; then
        echo "Pre-commit error: pattern '$PATTERN' is defined in files below"
        echo -e $OUTPUT;
        EXIT=1;
    fi
}

# warning if `console.` is defined in js|tt|html|htm
search_warning 'console\.' 'js\|tt\|html\|htm'

# warning if `!!!` is defined in js|tt|html|htm
search_warning '!!!' 'js\|tt\|html\|htm'

# warning if `=======` is defined
search_warning '======='

if [ $EXIT = 1 ]; then
    exit $EXIT;
fi
